---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ x_ipcviewer_path }}"
  register: x_ipcviewer_binary_register
  tags: x_ipcviewer

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ x_ipcviewer_binary_register.stat.path }} version
  args:
    executable: /bin/bash
  register: x_ipcviewer_version_register
  changed_when: false
  when: x_ipcviewer_binary_register.stat.exists
  tags: x_ipcviewer

- name: Install
  become: true
  tags: x_ipcviewer
  when: not x_ipcviewer_binary_register.stat.exists or (x_ipcviewer_version_register.stdout | default('')) != x_ipcviewer_version
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ x_ipcviewer_url }}"
        checksum: "{{ x_ipcviewer_checksum | default(omit) }}"
        dest: /tmp/x-ipcviewer.tar.gz
        mode: "0644"

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/x-ipcviewer.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/x-ipcviewer
        dest: "{{ x_ipcviewer_path }}"
        mode: "0755"
        remote_src: true
