# vim:ft=yaml.ansible
---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
      become: true
  roles:
    - role: itsnotgoodname.x_ipcviewer
      vars:
        x_ipcviewer_version: 0.2.0
